### PR TITLE
New count method

### PR DESCRIPTION
**Pull request by leocjj**
Count methods included in db_storage and file_storage.
Method get simplyfied.

### CODE REVIEW

**Review by kaelwebdev — COMMENTED** [review]
### the function count is fine but in the function get you need overwrite the information with this:        
        tmp_dict = self.all(cls)
        k = "{}.{}".format(cls.__name__, id)
        return tmp_dict.get(k)
{'State.050e8511-ea5f-40c8-b8e2-6ad27bd784bf': <models.state.State object at 0x7fa55241f630>}

**Comment by kaelwebdev** [comment]
then make a new commit with the correction without asking pull request again because in this it serves to send all the changes you need until the code is perfect.

**Comment by leocjj** [comment]
New commit to improve get function in file_storage.py
Ready for your pull request approval.

**Review by kaelwebdev — COMMENTED** [review]
perfect

**Pull request merged**
